import {GenerateHistory, IgnoredInHistory, HistoryIndex} from "../../../../src/index";
import {Column, PrimaryGeneratedColumn} from "typeorm";
import { EnumType } from "../enum/enumType";

@GenerateHistory({"historyPath": "./test/dist/_autogenerated_historymodels/heroes"})
export class Hero {
    @PrimaryGeneratedColumn()
    public id?: number;
    @Column("text")
    public name: string;
    @HistoryIndex("index_data_test")
    @Column("text")
    public data: string;
    @HistoryIndex()
    @Column()
    public detailId?: number;
    @Column({"type": "integer", "array": true, "nullable": true})
    public simpleArray: number[];
    @Column({"type": "text", "array": true, "nullable": true})
    public simpleStringArray: string[];
    public columnWithoutDatabase: string;
    @Column("smallint")
    public enuma: EnumType;
}
