"use strict";

import * as fs from "fs";
import {} from "mocha";
import {createHistoryModels} from "../../../src/index";
import {Options, FileMapping} from "../../../src/tasks/model/options";
import {expect} from "chai";


describe("E2E Tests", () => {

      it("Hero", (done) => {
        let expectedFileName = "./test/src/expected/hero/heroHistoryModel.ts",
            generatedFileName = "./test/dist/_autogenerated_historymodels/heroes/hero.ts",
            sourceFileName = "./test/src/model/hero/hero.ts";

        let options: Options = {
          files: [
            {
              source: sourceFileName,
              destination: generatedFileName
            }
          ]
        };

        createHistoryModels();
        let expected = fs.readFileSync(expectedFileName, "utf-8");
        let result = fs.readFileSync(generatedFileName, "utf-8");

        expect(result).be.equal(expected);

        done();
      });

});
